__project_name__ = 'upsies'
__description__ = 'Media metadata aggregator'
__homepage__ = 'https://upsies.readthedocs.io'
__version__ = '0.2.0dev6'
__author__ = 'plotski'
__author_email__ = 'plotski@example.org'
